### ISSUE TITLE
活動頁面 Google 地圖串接

### ISSUE THREAD

**Issue by Robeeerto** [magician-demo/rtix#9]
# 共有三個區塊
<img width="940" alt="截圖 2021-05-09 22 47 52" src="https://user-images.githubusercontent.com/74767965/117576501-d244fc80-b118-11eb-9530-c6a5b4bff7ec.png">

# 紅框為 Google Map 區塊

# 藍色框點擊後抵達 Google Map 頁面 左方能填入目前位置計算距離( 地址為活動地點 )
<img width="1438" alt="截圖 2021-05-09 22 51 10" src="https://user-images.githubusercontent.com/74767965/117576576-12a47a80-b119-11eb-8190-7700032f219b.png">

# 黃色框點擊會抵達活動地方的位置圖
<img width="1438" alt="截圖 2021-05-09 22 51 50" src="https://user-images.githubusercontent.com/74767965/117576659-44b5dc80-b119-11eb-9e6e-1aa618498881.png">

**Comment by skyee2021** [comment]
後改為僅顯示會場地址的google
